apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: poornima-tik-pipeline
spec:
  workspaces:
    - name: shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      default: https://github.com/cloud-native-garage-method-cohort/poornima-tik-repo
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/poornima-tik-repo
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: build-image
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: "$(params.image-repo)/poornima-tik-app:$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data